### PR TITLE
Correct casing of paintDirty flag

### PR DESCRIPTION
**Pull request by bean5**
**Expected**
Project can be built shortly after clone.

**Actual**
```
$fl build appbundle
Initializing gradle...                                              0.6s
Resolving dependencies...                                           1.3s
                                                                        
Compiler message:                                                       
lib/src/widgets/flare/desaturated_actor.dart:16:48: Error: Getter not found: 'PaintDirty'.
    artboard.addDirt(artboard.root, DirtyFlags.PaintDirty, true);       
                                               ^^^^^^^^^^               
Compiler terminated unexpectedly.                                       
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/bean/bin/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 739
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildReleaseArm'.         
> Process 'command '/home/bean/bin/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 8s                                                      
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                         9.0s
Gradle task bundleRelease failed with exit code 1
```

### CODE REVIEW

**Comment by bean5** [comment]
Fixes de7add6db648148bd066e4ef68743e392a8c0644

**Comment by bean5** [comment]
Actually, was probably introduced by a change in a library. Do we need to update the pubspec.yaml to restrict within semantic versions?

**Comment by rotter** [comment]
Someone please accept this fix. I'm new to Flutter and cloned the main repo and couldnt build, took me a few minutes to figure out this fix by myself.

**Comment by bean5** [comment]
@filiph

**Comment by bean5** [comment]
The fact that this is still open seems to indicate to me that this is rarely used, which is crazy. The app is a full fledged game open sourced.

That or somehow other machines don't run into this problem?

**Comment by rotter** [comment]
I have no idea if this applies to everyone, but from my specific point of view: 
1. I havent heard before about this project, found it by chance on a "advanced-ish" Google I/O video (so this wouldnt apply to total beginners anyway), so maybe a bit more of linking/spreading could be useful, and
2. This project seems to be huge/very complex, it will take me a lot of time to understand/grasp it, so it's unlikely I will benefit from it until I'm already much more advanced on Flutter/dart.

**Comment by luigi-rosso** [comment]
I'd bump it to the latest as it seems like everything is working there: ```flare_flutter: ^1.8.3```

**Comment by bean5** [comment]
@luigi-rosso So we can reject this branch?

**Comment by luigi-rosso** [comment]
No, sorry! I didn't make that clear. Your fix is good, but I'd recommend also bumping the flare_flutter version since 1.5.5 still has the old casing. If you could submit that small change I'll merge this in!

**Comment by bean5** [comment]
@luigi-rosso Done. I re-pushed everything since I amended the author data.

**Comment by luigi-rosso** [comment]
Thanks for the contribution, glad this is finally fixed. Sorry that it went unseen for so long!

**Comment by bean5** [comment]
You are welcome.

**Pull request merged**
